### ISSUE TITLE
Implement a ecplise-like autocomplete so when a user presses ctrl+space it auto fills the keyword

### ISSUE THREAD

**Issue by ianngiaw** [cs2103jan2015-w14-2j/main#64]

**Comment by hemolin** [comment]
Hi Ian, can I add in some basic aliases of command that will not handled by the auto-complete? For example "+" for "add"  and "-" for "delete".

**Comment by ianngiaw** [comment]
Considering that we have only 1 week left to the software demo, I believe this feature can be left out
